version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/vendor
